theme: minima
title: "My GitHub Blog"
author: "Mayur Yadawatti" 
description: " A digital diary of myself—life, embedded systems, and everything in between."
show_excerpts: true

# Custom CSS
theme: minima
plugins:
  - jekyll-feed

